server:
  port: 8090
eureka:
  instance:
    hostname: 172.19.201.177
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 10
  client:
    region: sz
    availability-zones:
      sz: default-zone
    registry-fetch-interval-seconds: 10
    serviceUrl:
      defaultZone: http://172.19.201.177:1122/eureka/
spring:
  application:
    name: warehouse
  profiles:
      active: dev

mybatis:
  typeAliasesPackage: com.rutong.warehouse
  mapperLocations: classpath:com/rutong/warehouse/persistence/*.xml

feign:
  httpclient:
    enable: true

---
spring:
  profiles: dev
  http:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB
  datasource:
    url: jdbc:postgresql://172.19.201.177:5432/test?charSet=utf-8
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
    type: com.alibaba.druid.pool.DruidDataSource
